# Generated by Django 5.2.9 on 2026-04-22 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel('SpaceAssignment'),
        migrations.DeleteModel('SpaceBooking'),
        migrations.DeleteModel('Polygon'),
        migrations.DeleteModel('Space'),
        migrations.DeleteModel('SpaceType'),
        migrations.DeleteModel('Floor'),
        migrations.DeleteModel('MapLayer'),
        migrations.DeleteModel('Building'),
    ]
