# Generated by Django 5.2.9 on 2026-04-21 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AntennaEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Equipment Name')),
                ('sub_elements', models.CharField(blank=True, max_length=255, verbose_name='Sub Elements')),
                ('responsible_person', models.CharField(max_length=255, verbose_name='Responsible Person')),
                ('status', models.CharField(blank=True, max_length=50, verbose_name='Status')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Region')),
                ('building_height', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Building Height (m)')),
                ('mast_height', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Mast Height (m)')),
                ('comments', models.TextField(blank=True, verbose_name='Comments')),
                ('item_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Item ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Antenna Equipment',
                'verbose_name_plural': 'Antenna Equipment',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AntennaSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antenna_type', models.CharField(choices=[('4G', '4G'), ('5G', '5G')], max_length=10, verbose_name='Antenna Type')),
                ('height_mm', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Height (mm)')),
                ('width_mm', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Width (mm)')),
                ('thickness_mm', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Thickness (mm)')),
                ('weight_dan', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Weight (daN)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='geodata.antennaequipment', verbose_name='Equipment')),
            ],
            options={
                'verbose_name': 'Antenna Specification',
                'verbose_name_plural': 'Antenna Specifications',
                'ordering': ['equipment', 'antenna_type'],
                'unique_together': {('equipment', 'antenna_type')},
            },
        ),
        migrations.CreateModel(
            name='TerrainLoadCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terrain_type', models.CharField(choices=[('0', 'Terrain 0'), ('II', 'Terrain II'), ('IIIa', 'Terrain IIIa'), ('IIIb', 'Terrain IIIb'), ('IV', 'Terrain IV')], max_length=10, verbose_name='Terrain Type')),
                ('section_material', models.CharField(blank=True, max_length=255, verbose_name='Section Material')),
                ('load_calculations', models.JSONField(blank=True, default=dict, verbose_name='Load Calculations')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terrain_calculations', to='geodata.antennaequipment', verbose_name='Equipment')),
            ],
            options={
                'verbose_name': 'Terrain Load Calculation',
                'verbose_name_plural': 'Terrain Load Calculations',
                'ordering': ['equipment', 'terrain_type'],
                'unique_together': {('equipment', 'terrain_type')},
            },
        ),
    ]
