# Generated by Django 5.2.9 on 2026-04-22 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='antennaequipment',
            name='responsible_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_responsible', to=settings.AUTH_USER_MODEL, verbose_name='Responsible User'),
        ),
        migrations.AlterField(
            model_name='antennaequipment',
            name='responsible_person',
            field=models.CharField(blank=True, max_length=255, verbose_name='Responsible Person'),
        ),
    ]
