# Generated by Django 5.2.9 on 2026-04-22 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0002_antennaequipment_responsible_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrainloadcalculation',
            name='material_specification',
            field=models.CharField(blank=True, help_text="Material section specification (e.g., '139x6.3mm')", max_length=255, verbose_name='Material Specification'),
        ),
        migrations.CreateModel(
            name='TerrainDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terrain_type', models.CharField(choices=[('0', 'Terrain 0'), ('II', 'Terrain II'), ('IIIa', 'Terrain IIIa'), ('IIIb', 'Terrain IIIb'), ('IV', 'Terrain IV')], max_length=10, verbose_name='Terrain Type')),
                ('document_urls', models.TextField(help_text='Comma-separated URLs for terrain calculation documents', verbose_name='Document URLs')),
                ('document_types', models.JSONField(blank=True, default=list, help_text="List of document file extensions (e.g., ['.docx', '.rtd'])", verbose_name='Document Types')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Upload Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terrain_documentations', to='geodata.antennaequipment', verbose_name='Equipment')),
            ],
            options={
                'verbose_name': 'Terrain Documentation',
                'verbose_name_plural': 'Terrain Documentations',
                'ordering': ['equipment', 'terrain_type'],
                'unique_together': {('equipment', 'terrain_type')},
            },
        ),
        migrations.AddField(
            model_name='terrainloadcalculation',
            name='documentation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='load_calculation', to='geodata.terraindocumentation', verbose_name='Documentation'),
        ),
    ]
