# Generated by Django 5.2.9 on 2026-04-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0003_terrainloadcalculation_material_specification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antennaequipment',
            name='region',
            field=models.IntegerField(blank=True, choices=[(1, 'Region 1'), (2, 'Region 2'), (3, 'Region 3'), (4, 'Region 4')], null=True, verbose_name='Region'),
        ),
    ]
